# Generated by Django 5.1 on 2024-09-01 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnePage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactrequest',
            old_name='email',
            new_name='Endereço_Email',
        ),
        migrations.RenameField(
            model_name='contactrequest',
            old_name='message',
            new_name='Mensagem',
        ),
        migrations.RenameField(
            model_name='contactrequest',
            old_name='name',
            new_name='Nome_Completo',
        ),
        migrations.RenameField(
            model_name='contactrequest',
            old_name='phone',
            new_name='Numero_de_telefone',
        ),
    ]
