# Generated by Django 5.1 on 2024-09-01 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnePage', '0002_rename_email_contactrequest_endereço_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactRequest',
            new_name='Mensagem',
        ),
    ]
