# Generated by Django 5.1 on 2024-09-02 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnePage', '0003_rename_contactrequest_mensagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensagem',
            old_name='Mensagem',
            new_name='mensagem',
        ),
    ]
