# Generated by Django 5.1 on 2024-10-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnePage', '0005_portfolioitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='category',
            field=models.CharField(choices=[('e-commerce', 'E-commerce'), ('blog', 'Blog'), ('onepage', 'OnePage'), ('landing page', 'Landing Page'), ('outros', 'Outros')], max_length=100),
        ),
    ]
