# Generated by Django 5.1 on 2025-03-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnePage', '0007_portfolioitem_completion_date_portfolioitem_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='data',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
