# Generated by Django 5.1 on 2025-03-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnePage', '0008_alter_portfolioitem_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='case_study',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='case_study_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='has_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/videos/'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='category',
            field=models.CharField(choices=[('e-commerce', 'E-commerce'), ('blog', 'Blog'), ('onepage', 'OnePage'), ('landing page', 'Landing Page'), ('video', 'Vídeos'), ('outros', 'Outros')], max_length=100),
        ),
    ]
