# Generated by Django 5.0.2 on 2025-04-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnePage', '0009_portfolioitem_case_study_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('foto', models.ImageField(upload_to='media/fotos/')),
            ],
        ),
    ]
