# Generated by Django 5.0.2 on 2025-04-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnePage', '0010_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Briefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('tipo_projeto', models.CharField(choices=[('site', 'Desenvolvimento de Site'), ('chatbot', 'Chatbot com IA'), ('google_negocio', 'Consultoria Google Meu Negócio'), ('ifood', 'Consultoria para iFood'), ('trafego', 'Tráfego Pago'), ('redes', 'Consultoria para Redes Sociais'), ('logo', 'Criação de Logotipo'), ('outro', 'Outro')], max_length=20)),
                ('objetivo', models.TextField()),
                ('funcionalidades', models.TextField(blank=True)),
                ('referencias', models.TextField(blank=True)),
                ('orcamento', models.CharField(choices=[('1000-1500', 'R$1.000 a R$1.500'), ('1500-3000', 'R$1.500 a R$3.000'), ('3000-6000', 'R$3.000 a R$6.000'), ('sob_consulta', 'A definir / Sob consulta')], max_length=20)),
                ('prazo', models.CharField(choices=[('1-2', '1-2 semanas'), ('2-4', '2-4 semanas'), ('4-8', '4-8 semanas'), ('flexivel', 'Prazo flexível')], max_length=20)),
                ('experiencia', models.CharField(choices=[('iniciante', 'Sou iniciante, preciso de orientação'), ('intermediario', 'Já tenho alguma experiência'), ('avancado', 'Já participei de projetos semelhantes')], max_length=20)),
                ('mensagem_final', models.TextField(blank=True)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
